spring:
  application:
    name: mushroom
  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/mushroom?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 514179
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

springdoc:
  swagger-ui:
    path: /swagger-ui.html